# Generated by Django 4.1 on 2022-08-05 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_creator_comapany", models.IntegerField(blank=True, null=True)),
                ("institute_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("test_code", models.CharField(max_length=255)),
                ("track", models.CharField(max_length=255)),
                ("interaction_mode", models.CharField(max_length=255)),
                ("report_type", models.CharField(max_length=255)),
                (
                    "report_type_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("generate_certificate", models.CharField(max_length=255)),
                (
                    "generate_certificate_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("job_instruction", models.CharField(max_length=255)),
                ("job_describtion", models.CharField(max_length=255)),
                ("access_code", models.CharField(max_length=255)),
                ("expiry_date", models.DateField()),
                ("who_can_initiate", models.CharField(max_length=255)),
                ("timer", models.CharField(max_length=255)),
                ("collect_mail", models.BooleanField()),
                ("collect_resume", models.BooleanField()),
                ("collect_candidate_feedback_message", models.BooleanField()),
                ("collect_channel", models.CharField(max_length=255)),
                ("collect_candidate_id", models.BooleanField()),
                ("collect_voice_match", models.BooleanField()),
                ("total_question", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "createdby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_craeted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updatedby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer_format", models.CharField(max_length=255)),
                ("ideal_answer", models.CharField(max_length=255)),
                ("rated", models.BooleanField()),
                ("content_rated", models.BooleanField(blank=True, null=True)),
                ("should_score", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mcq_option_one",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "mcq_option_two",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "mcq_option_three",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "mcq_option_four",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_craeted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.test"
                    ),
                ),
                (
                    "updatedby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interaction_welcome_message", models.CharField(max_length=255)),
                ("interaction_instruction_message", models.CharField(max_length=255)),
                ("interaction_completion_message", models.CharField(max_length=255)),
                ("bot_warning_message", models.CharField(max_length=255)),
                ("report_send_to_user", models.BooleanField()),
                (
                    "report_sent_to_email_one",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "report_sent_to_email_two",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "createdby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.test"
                    ),
                ),
                (
                    "updatedby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
