# Generated by Django 4.1 on 2022-08-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_question_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="backend.test",
            ),
        ),
    ]
