# Generated by Django 4.1 on 2022-08-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_alter_interaction_candidate_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="channel_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="channel_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
