# Generated by Django 4.1 on 2022-08-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_interaction_channel_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
