# Generated by Django 4.1 on 2022-08-12 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0013_candidate_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invitation_code",
                    models.CharField(
                        blank=True,
                        help_text="This code tell us which user is invite this user.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("invitation_code_optional", models.BooleanField(default=False)),
                (
                    "invite_code",
                    models.CharField(
                        help_text="This is the code with that user can invite the other user.",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
