# Generated by Django 4.0.2 on 2022-08-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0016_scoreperquestion_textscoreperquestion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audioscore",
            old_name="audio_aggregate_content_scoe",
            new_name="audio_aggregate_content_score",
        ),
    ]
