# Generated by Django 4.1 on 2022-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0019_remove_audioscoreperquestion_question_score_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="charm_aggregate",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="score",
            name="confidence_aggregate",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="score",
            name="energy_aggregate",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="score",
            name="fluency_agreegate",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="score",
            name="likeability_aggregate",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
