# Generated by Django 4.1 on 2022-09-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0021_userdetail_country_userdetail_facebook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="rating_description",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="interaction",
            name="start_rating",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="interaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("response-received", "response-received"),
                    ("in-progress", "in-progress"),
                    ("done", "done"),
                ],
                default="response-received",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="media_link",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_context",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="external_bot",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="insights",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="mentor_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="user_type",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="country",
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="facebook_url",
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="instagram_url",
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="institute_name",
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="linkedin_url",
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="phone_number",
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="twitter_url",
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
    ]
