# Generated by Django 4.1 on 2022-09-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0022_interaction_rating_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interaction",
            name="status",
        ),
        migrations.AddField(
            model_name="response",
            name="status",
            field=models.CharField(
                choices=[
                    ("response-received", "response-received"),
                    ("in-progress", "in-progress"),
                    ("done", "done"),
                ],
                default="response-received",
                max_length=255,
            ),
        ),
    ]
