# Generated by Django 4.1 on 2022-09-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_remove_interaction_status_response_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.CharField(max_length=255)),
                ('number_of_interaction', models.CharField(max_length=255)),
                ('number_of_responses_per_test', models.CharField(max_length=255)),
                ('employee', models.BooleanField()),
                ('expiry_date', models.CharField(blank=True, max_length=255, null=True)),
                ('external_bot_user', models.BooleanField()),
                ('video_creator', models.BooleanField()),
                ('team_user', models.BooleanField()),
                ('one_time_user', models.BooleanField()),
                ('user_type', models.CharField(max_length=255)),
            ],
        ),
    ]
