# Generated by Django 4.1 on 2022-11-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_businessinvitationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='business_invite_code',
            field=models.CharField(blank=True, default=None, help_text='This is the code with that user signed up in the signup page.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='external_bot_user',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='number_of_interaction',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='number_of_responses',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='video_creator',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
