# Generated by Django 4.1 on 2022-11-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_userdetail_business_invite_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='report_send_to_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='report_sent_to_email_one',
        ),
        migrations.AddField(
            model_name='test',
            name='report_sent_to_candidate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='report_sent_to_email_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='generate_certificate',
            field=models.BooleanField(default=True),
        ),
    ]
