# Generated by Django 4.1 on 2022-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_remove_notification_report_send_to_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='assesment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='library',
            field=models.BooleanField(default=False),
        ),
    ]
